security:

    role_hierarchy:
        ROLE_MEMBER:          ROLE_USER
        ROLE_CLIENT:          ROLE_MEMBER
        ROLE_MANAGER:         ROLE_CLIENT
        ROLE_ADMIN:           ROLE_MANAGER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class:  App\Entity\User
                # property: username
                # if you're using multiple entity managers
                # manager_name: customer

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:  ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path:  login
                check_path:  login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:     /logout
                target:   /
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_MANAGER }